# Generated by Django 5.2.6 on 2025-12-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_no', models.CharField(max_length=10, unique=True)),
                ('dob', models.DateField()),
                ('pwd', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
    ]
