# Generated by Django 5.2.6 on 2025-11-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.TextField(max_length=250)),
                ('contact_no', models.CharField(max_length=15, unique=True)),
                ('dob', models.DateField()),
                ('pwd', models.CharField(max_length=266)),
                ('c_pwd', models.CharField(max_length=266)),
                ('gender', models.CharField(max_length=255)),
            ],
        ),
    ]
